apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: {{ .Values.mongo.replicaset }}
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
            - name: mongo
              image: {{ .Values.mongo.image }}
              # resources:
              #   limits:
              #   memory: "128Mi"
              #   cpu: "500m"
              ports:
              - containerPort: {{ .Values.mongo.port }}