apiVersion: v1
kind: Service
metadata:
  name: service-app
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      nodePort: {{ .Values.app.service.nodeport }}
